name: CI

on:
  pull_request:
  push:
    branches: [ "test_ci" ]
  pull_request:
    branches: [ "test_ci" ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  check:
    runs-on: ubuntu-latest
  #  strategy:
    #  matrix:
  #      suite: ['base', 'main:suite-1', 'main:suite-2', 'fiori']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install Dependencies
      run: cd sap-alm-dp-api-datasource && pwd && yarn --version

  #  - name: Build
  #    run: cd sap-alm-dp-api-datasource && yarn build
  #    env:
  #      ENABLE_CLDR: 1

  #  - name: Test
  #    run: cd sap-alm-dp-api-datasource && yarn test:${{ matrix.suite }}
